const CHILD_READY = 'CHILD_READY';
const USER_CONNECTED = 'USER_CONNECTED';
const INVOKE_HANDLER = 'INVOKE_HANDLER';
const V8_INSPECTOR_MESSAGE = 'V8_INSPECTOR_MESSAGE';
const SET_CALLBACKWAITSFOREMPTYEVENTLOOP = 'SET_CALLBACKWAITSFOREMPTYEVENTLOOP';
const LAMBDA_CALLBACK = 'LAMBDA_CALLBACK';

module.exports = {
  CHILD_READY,
  USER_CONNECTED,
  INVOKE_HANDLER,
  V8_INSPECTOR_MESSAGE,
  SET_CALLBACKWAITSFOREMPTYEVENTLOOP,
  LAMBDA_CALLBACK,
};
